🐛 fix(display): Call isElectron signal as function
The isElectron property is an Angular Signal that must be called as a
function to get its value. Fixes TypeScript error TS2774: "This condition
will always return true since this function is always defined."